model_parameters=list()
model_parameters$names                             =c('alpha','beta','lambda1')
model_parameters$transformation                    =c('logit','none','none')
model_parameters$artificial_population_location    =c(-0.8,4,3)
model_parameters$artificial_population_scale       =c(0.2,0.2,1)
