model_parameters=list()
model_parameters$names                             =c('alpha_key','alpha_color','alpha_shape','alpha_texture','beta_key','beta_visual')
model_parameters$transformation                    =c('logit','logit','logit','logit','none','none')
model_parameters$artificial_population_location    =c(0.5,0.5,0.5,0.5,4,20)
model_parameters$artificial_population_scale       =c(1,1,1,1,1.5,1.5)
