model_parameters=list()
model_parameters$names                             =c('alpha_relevant','alpha_irrelevant','beta')
model_parameters$transformation                    =c('logit','logit','none')
model_parameters$artificial_population_location    =c(0,0,3)
model_parameters$artificial_population_scale       =c(1,1,1)
