model_parameters=list()
model_parameters$names                             =c('alpha','beta','eta_dis','eta_con')
model_parameters$transformation                    =c('logit','none','logit','logit')
model_parameters$artificial_population_location    =c(0.3,4,0.3,0.3)
model_parameters$artificial_population_scale       =c(0.3,1.5,0.3,0.3)
