model_stan_parameters=list()
model_stan_parameters$parameters=c(
  'first_trial_in_block', 
  'block',
  'trial',
  'key1',
  'key2',
  'color1',
  'color2',
  'shape1',
  'shape2',
  'texture1',
  'texture2',
  'ch_key',
  'ch_color',
  'ch_shape',
  'ch_texture',
  'selected_offer',
  'reward'
  )
