model_parameters=list()
model_parameters$names                             =c('alpha','alpha_task','beta','eta')
model_parameters$transformation                    =c('logit','logit','none','logit')
model_parameters$artificial_population_location    =c(0.5,0.5,3,0.5)
model_parameters$artificial_population_scale       =c(0.3,0.3,1.5,0.3)
