model_parameters=list()
model_parameters$names                             =c('alpha_relevant','alpha_irrelevant','beta','lambda1','lambda2')
model_parameters$transformation                    =c('logit','logit','none','none','none')
model_parameters$artificial_population_location    =c(-0.8,-2,4,3,3)
model_parameters$artificial_population_scale       =c(0.1,0.5,0.1,0.1,0.1)
